// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@2.0.4";

// src/lib/mcp/tools/list-products.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@2.0.4";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.95.3";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseAnon() {
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-products.ts
var list_products_default = defineTool({
  name: "list_products",
  title: "List products",
  description: "List the OmniaVital ritual products with pricing, category and tagline.",
  inputSchema: {
    category: z.string().trim().optional().describe("Optional category filter, e.g. morning, focus or evening.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ category }) => {
    const supabase = supabaseAnon();
    let query = supabase.from("products").select("id, slug, name, tagline, description, category, price").order("name");
    if (category) query = query.eq("category", category);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { products: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-product.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@2.0.4";
import { z as z2 } from "npm:zod@^3.25.76";
var get_product_default = defineTool2({
  name: "get_product",
  title: "Get product",
  description: "Get full detail for one OmniaVital product by its slug.",
  inputSchema: { slug: z2.string().trim().min(1).describe("Product slug, e.g. morning-protocol.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ slug }) => {
    const supabase = supabaseAnon();
    const { data, error } = await supabase.from("products").select("*").eq("slug", slug).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: `No product with slug "${slug}".` }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { product: data }
    };
  }
});

// src/lib/mcp/tools/get-my-profile.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@2.0.4";
var get_my_profile_default = defineTool3({
  name: "get_my_profile",
  title: "Get my profile",
  description: "Get the signed-in member's OmniaVital profile (name, OV tag).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("profiles").select("first_name, ov_tag, avatar_url, created_at").eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify({ email: ctx.getUserEmail(), ...data }) }],
      structuredContent: { profile: data ?? null }
    };
  }
});

// src/lib/mcp/tools/list-my-purchases.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@2.0.4";
var list_my_purchases_default = defineTool4({
  name: "list_my_purchases",
  title: "List my purchases",
  description: "List the signed-in member's OmniaVital orders with product names and totals.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("purchases").select("id, quantity, total, status, purchased_at, products(name, slug, category)").eq("user_id", ctx.getUserId()).order("purchased_at", { ascending: false });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { purchases: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/log-ritual.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@2.0.4";
import { z as z3 } from "npm:zod@^3.25.76";
var log_ritual_default = defineTool5({
  name: "log_ritual",
  title: "Log a ritual",
  description: "Record a completed (or skipped) ritual for the signed-in member on a given date.",
  inputSchema: {
    product_slug: z3.string().trim().min(1).describe("Slug of the ritual product, e.g. morning-protocol."),
    logged_date: z3.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().describe("Date in YYYY-MM-DD. Defaults to today."),
    completed: z3.boolean().default(true).describe("Whether the ritual was completed."),
    notes: z3.string().trim().max(500).optional().describe("Optional note about the ritual.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ product_slug, logged_date, completed, notes }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data: product, error: productError } = await supabase.from("products").select("id, name").eq("slug", product_slug).maybeSingle();
    if (productError) return { content: [{ type: "text", text: productError.message }], isError: true };
    if (!product) {
      return { content: [{ type: "text", text: `No product with slug "${product_slug}".` }], isError: true };
    }
    const date = logged_date ?? (/* @__PURE__ */ new Date()).toISOString().slice(0, 10);
    const { data, error } = await supabase.from("ritual_logs").upsert(
      {
        user_id: ctx.getUserId(),
        product_id: product.id,
        logged_date: date,
        completed,
        notes: notes ?? null
      },
      { onConflict: "user_id,product_id,logged_date" }
    ).select().maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [
        {
          type: "text",
          text: `Logged ${product.name} as ${completed ? "taken" : "skipped"} for ${date}. It now shows on the member's ritual calendar.`
        }
      ],
      structuredContent: { log: data }
    };
  }
});

// src/lib/mcp/tools/get-ritual-streak.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@2.0.4";
function ringFor(streak) {
  if (streak >= 60) return "Gold Ring";
  if (streak >= 21) return "Silver Ring";
  if (streak >= 7) return "Bronze Ring";
  return "Building toward Bronze Ring (7 days)";
}
var get_ritual_streak_default = defineTool6({
  name: "get_ritual_streak",
  title: "Get my ritual streak",
  description: "Get the signed-in member's current daily ritual streak, ring status and today's progress.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("ritual_logs").select("logged_date, completed").eq("user_id", ctx.getUserId()).eq("completed", true).order("logged_date", { ascending: false }).limit(365);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const logs = data ?? [];
    const uniqueDates = [...new Set(logs.map((l) => l.logged_date))].sort().reverse();
    let streak = 0;
    for (let i = 0; i < uniqueDates.length; i++) {
      const expected = /* @__PURE__ */ new Date();
      expected.setDate(expected.getDate() - i);
      if (uniqueDates[i] === expected.toISOString().slice(0, 10)) streak++;
      else break;
    }
    const today = (/* @__PURE__ */ new Date()).toISOString().slice(0, 10);
    const completedToday = logs.filter((l) => l.logged_date === today).length;
    const result = { streak, ring: ringFor(streak), completedToday, activeDays: uniqueDates.length };
    return {
      content: [{ type: "text", text: JSON.stringify(result) }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/tools/list-community-posts.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@2.0.4";
import { z as z4 } from "npm:zod@^3.25.76";
var list_community_posts_default = defineTool7({
  name: "list_community_posts",
  title: "List community posts",
  description: "List recent discussion threads in The Collective community forum.",
  inputSchema: {
    category: z4.string().trim().optional().describe("Optional category filter."),
    limit: z4.number().int().min(1).max(50).default(20).describe("Maximum threads to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ category, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("forum_posts").select("id, title, body, category, parent_id, created_at").is("parent_id", null).order("created_at", { ascending: false }).limit(limit);
    if (category) query = query.eq("category", category);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { posts: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-community-post.ts
import { defineTool as defineTool8 } from "npm:@lovable.dev/mcp-js@2.0.4";
import { z as z5 } from "npm:zod@^3.25.76";
var create_community_post_default = defineTool8({
  name: "create_community_post",
  title: "Create community post",
  description: "Post a new thread, or a reply, in The Collective community forum as the signed-in member.",
  inputSchema: {
    title: z5.string().trim().min(1).max(160).describe("Thread title."),
    body: z5.string().trim().min(1).max(4e3).describe("Post body."),
    category: z5.string().trim().default("general").describe("Forum category."),
    parent_id: z5.string().uuid().optional().describe("Thread id when replying to an existing thread.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ title, body, category, parent_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("forum_posts").insert({ user_id: ctx.getUserId(), title, body, category, parent_id: parent_id ?? null }).select().maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Posted "${title}".` }],
      structuredContent: { post: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "lsladukwqwpwdxcnbvea";
var mcp_default = defineMcp({
  name: "vitality-gateway",
  title: "Vitality Gateway",
  version: "0.1.0",
  instructions: "Tools for OmniaVital. Browse the ritual product catalog, and for the signed-in member: read their profile and orders, log daily rituals, check their streak and ring status, and read or post in The Collective community forum.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_products_default,
    get_product_default,
    get_my_profile_default,
    list_my_purchases_default,
    log_ritual_default,
    get_ritual_streak_default,
    list_community_posts_default,
    create_community_post_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@2.0.4/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
